# Generated by Django 5.1.2 on 2024-12-27 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('mean', models.JSONField(blank=True, null=True)),
                ('median', models.JSONField(blank=True, null=True)),
                ('mode', models.JSONField(blank=True, null=True)),
                ('variance', models.JSONField(blank=True, null=True)),
                ('std_dev', models.JSONField(blank=True, null=True)),
                ('range_values', models.JSONField(blank=True, null=True)),
                ('histograms', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_histories', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analyse.uploadedfile')),
            ],
            options={
                'verbose_name': 'Analysis History',
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['upload_date'], name='analyse_ana_upload__7372f3_idx'), models.Index(fields=['status'], name='analyse_ana_status_83fe5a_idx')],
            },
        ),
    ]
