# Generated by Django 5.1.2 on 2025-01-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
