# Generated by Django 5.1.2 on 2024-11-02 13:38

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyse", "0002_analysishistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="histograms",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
