# Generated by Django 5.1.2 on 2025-01-10 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_delete_analysishistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('mean', models.JSONField(blank=True, null=True)),
                ('median', models.JSONField(blank=True, null=True)),
                ('mode', models.JSONField(blank=True, null=True)),
                ('variance', models.JSONField(blank=True, null=True)),
                ('std_dev', models.JSONField(blank=True, null=True)),
                ('coefficient_of_variation', models.JSONField(blank=True, null=True)),
                ('skewness', models.JSONField(blank=True, null=True)),
                ('kurtosis', models.JSONField(blank=True, null=True)),
                ('range_values', models.JSONField(blank=True, null=True)),
                ('histograms', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyse.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis History',
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['upload_date'], name='analyse_ana_upload__7372f3_idx'), models.Index(fields=['status'], name='analyse_ana_status_83fe5a_idx')],
            },
        ),
    ]
