# Generated by Django 5.1.2 on 2024-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_analysishistory_histograms'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
