# Generated by Django 5.1.2 on 2024-12-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyse", "0004_analysishistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="range_values",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
