# Generated by Django 5.1.2 on 2024-12-07 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyse", "0005_analysishistory_range_values"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysishistory",
            options={
                "ordering": ["-upload_date"],
                "verbose_name": "Analysis History",
                "verbose_name_plural": "Analysis Histories",
            },
        ),
        migrations.RemoveField(
            model_name="analysishistory",
            name="file",
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="analyse.uploadedfile",
            ),
        ),
        migrations.AlterField(
            model_name="analysishistory",
            name="histograms",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysishistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="analysishistory",
            index=models.Index(
                fields=["upload_date"], name="analyse_ana_upload__7372f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysishistory",
            index=models.Index(fields=["status"], name="analyse_ana_status_83fe5a_idx"),
        ),
    ]
